// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniRest.Api.Data;

#nullable disable

namespace OmniRest.Api.Data.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20260731044751_Pr5MenuBrowsing")]
    partial class Pr5MenuBrowsing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniRest.Api.Data.BadgeEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_key");

                    b.HasKey("RestaurantId", "Code");

                    b.ToTable("badges", "public", t =>
                        {
                            t.HasCheckConstraint("ck_badges_category", "category IN ('dietary', 'allergen', 'promotional', 'heat')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishBadgeEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<string>("BadgeCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("badge_code");

                    b.HasKey("RestaurantId", "DishId", "BadgeCode");

                    b.HasIndex("DishId", "RestaurantId");

                    b.HasIndex("RestaurantId", "BadgeCode");

                    b.ToTable("dish_badges", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("available")
                        .HasColumnName("availability_status");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("MediaAssetId", "RestaurantId");

                    b.HasIndex("CategoryId", "MenuId", "RestaurantId");

                    b.HasIndex("RestaurantId", "MenuId", "CategoryId", "IsActive", "ArchivedAt", "DisplayOrder");

                    b.ToTable("dishes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_dishes_availability", "availability_status IN ('available', 'unavailable')");

                            t.HasCheckConstraint("ck_dishes_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_dishes_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_dishes_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("media_assets", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaVariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("MediaAssetId", "RestaurantId");

                    b.HasIndex("MediaAssetId", "Width", "Height")
                        .IsUnique();

                    b.ToTable("media_variants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_media_variants_dimensions", "width > 0 AND height > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MenuId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("MenuId", "RestaurantId");

                    b.HasIndex("MenuId", "Slug")
                        .IsUnique();

                    b.HasIndex("Id", "MenuId", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("RestaurantId", "MenuId", "IsActive", "DisplayOrder");

                    b.ToTable("menu_categories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_menu_categories_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_menu_categories_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_menu_categories_slug", "slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasFilter("is_active");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("menus", "public", t =>
                        {
                            t.HasCheckConstraint("ck_menus_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasFilter("is_current");

                    b.HasIndex("RestaurantId", "Version")
                        .IsUnique();

                    b.ToTable("publications", "public", t =>
                        {
                            t.HasCheckConstraint("ck_publications_version", "version > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantDomainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("restaurant_domains", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_domains_normalized", "host = lower(host) AND host !~ '[:/\\s]'");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("restaurants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurants_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantSettingsEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<string>("TaxDisplayMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tax_display_mode");

                    b.Property<string>("TaxNoticeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_notice_key");

                    b.HasKey("RestaurantId");

                    b.ToTable("restaurant_settings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_settings_tax_mode", "tax_display_mode IN ('inclusive', 'exclusive')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.BadgeEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishBadgeEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.DishEntity", "Dish")
                        .WithMany("Badges")
                        .HasForeignKey("DishId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniRest.Api.Data.BadgeEntity", "Badge")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BadgeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MediaAssetEntity", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniRest.Api.Data.MenuCategoryEntity", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId", "MenuId", "RestaurantId")
                        .HasPrincipalKey("Id", "MenuId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaVariantEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MediaAssetEntity", "MediaAsset")
                        .WithMany("Variants")
                        .HasForeignKey("MediaAssetId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MenuEntity", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Publications")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantDomainEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Domains")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantSettingsEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithOne("Settings")
                        .HasForeignKey("OmniRest.Api.Data.RestaurantSettingsEntity", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.Navigation("Badges");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantEntity", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Menus");

                    b.Navigation("Publications");

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
