// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniRest.Api.Data;

#nullable disable

namespace OmniRest.Api.Data.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    partial class MenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("owner_roles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("owner_role_claims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("owner_user_claims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("owner_user_logins", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("owner_user_roles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("owner_user_tokens", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_version");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "OccurredAt");

                    b.ToTable("audit_events", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.BadgeEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_key");

                    b.HasKey("RestaurantId", "Code");

                    b.ToTable("badges", "public", t =>
                        {
                            t.HasCheckConstraint("ck_badges_category", "category IN ('dietary', 'allergen', 'promotional', 'heat')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishBadgeEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<string>("BadgeCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("badge_code");

                    b.HasKey("RestaurantId", "DishId", "BadgeCode");

                    b.HasIndex("DishId", "RestaurantId");

                    b.HasIndex("RestaurantId", "BadgeCode");

                    b.ToTable("dish_badges", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("available")
                        .HasColumnName("availability_status");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("MediaAssetId", "RestaurantId");

                    b.HasIndex("CategoryId", "MenuId", "RestaurantId");

                    b.HasIndex("RestaurantId", "MenuId", "CategoryId", "IsActive", "ArchivedAt", "DisplayOrder");

                    b.ToTable("dishes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_dishes_availability", "availability_status IN ('available', 'unavailable')");

                            t.HasCheckConstraint("ck_dishes_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_dishes_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_dishes_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ready")
                        .HasColumnName("processing_status");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("media_assets", "public", t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_processing_status", "processing_status IN ('pending', 'ready', 'failed')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaVariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("MediaAssetId", "RestaurantId");

                    b.HasIndex("MediaAssetId", "Width", "Height")
                        .IsUnique();

                    b.ToTable("media_variants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_media_variants_dimensions", "width > 0 AND height > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MenuId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("MenuId", "RestaurantId");

                    b.HasIndex("MenuId", "Slug")
                        .IsUnique();

                    b.HasIndex("Id", "MenuId", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("RestaurantId", "MenuId", "IsActive", "DisplayOrder");

                    b.ToTable("menu_categories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_menu_categories_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_menu_categories_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_menu_categories_slug", "slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasFilter("is_active");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("menus", "public", t =>
                        {
                            t.HasCheckConstraint("ck_menus_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.OwnerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentSessionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_session_started_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("owner_users", "public");
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("operation_id IS NOT NULL");

                    b.HasIndex("RestaurantId")
                        .IsUnique()
                        .HasFilter("is_current");

                    b.HasIndex("RestaurantId", "Version")
                        .IsUnique();

                    b.ToTable("publications", "public", t =>
                        {
                            t.HasCheckConstraint("ck_publications_version", "version > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationOutboxEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DraftSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("draft_snapshot");

                    b.Property<long>("DraftVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("draft_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OperationId");

                    b.HasIndex("RestaurantId", "DraftVersion")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("publication_outbox", "public", t =>
                        {
                            t.HasCheckConstraint("ck_publication_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_publication_outbox_status", "status IN ('pending', 'processing', 'succeeded', 'failed')");

                            t.HasCheckConstraint("ck_publication_outbox_version", "draft_version > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RegularHourIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "DayOfWeek", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("regular_hour_intervals", "public", t =>
                        {
                            t.HasCheckConstraint("ck_regular_hours_day", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_regular_hours_duration", "opens_at <> closes_at");

                            t.HasCheckConstraint("ck_regular_hours_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantAddressEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("line2");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.HasKey("RestaurantId");

                    b.ToTable("restaurant_addresses", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_addresses_coordinates", "(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantDomainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.ToTable("restaurant_domains", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_domains_normalized", "host = lower(host) AND host !~ '[:/\\s]'");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<long>("DraftVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("draft_version");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("MainMediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_media_asset_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneDisplay")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_display");

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MainMediaAssetId", "Id");

                    b.ToTable("restaurants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurants_draft_version", "draft_version > 0");

                            t.HasCheckConstraint("ck_restaurants_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_restaurants_phone_e164", "phone_e164 IS NULL OR phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Status");

                    b.HasIndex("UserId", "RestaurantId")
                        .IsUnique();

                    b.ToTable("restaurant_memberships", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_memberships_role", "role IN ('owner')");

                            t.HasCheckConstraint("ck_restaurant_memberships_status", "status IN ('active', 'revoked')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantSettingsEntity", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<string>("TaxDisplayMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tax_display_mode");

                    b.Property<string>("TaxNoticeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_notice_key");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Winnipeg")
                        .HasColumnName("time_zone_id");

                    b.HasKey("RestaurantId");

                    b.ToTable("restaurant_settings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_restaurant_settings_tax_mode", "tax_display_mode IN ('inclusive', 'exclusive')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.SocialLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Platform")
                        .IsUnique();

                    b.ToTable("social_links", "public", t =>
                        {
                            t.HasCheckConstraint("ck_social_links_platform", "platform IN ('instagram', 'facebook', 'tiktok', 'google_business')");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.SpecialHourEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("Id", "RestaurantId")
                        .IsUnique();

                    b.HasIndex("RestaurantId", "Date")
                        .IsUnique();

                    b.ToTable("special_hours", "public", t =>
                        {
                            t.HasCheckConstraint("ck_special_hours_note", "note IS NULL OR length(btrim(note)) > 0");
                        });
                });

            modelBuilder.Entity("OmniRest.Api.Data.SpecialHourIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("SpecialHourId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_hour_id");

                    b.HasKey("Id");

                    b.HasIndex("SpecialHourId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("SpecialHourId", "RestaurantId");

                    b.ToTable("special_hour_intervals", "public", t =>
                        {
                            t.HasCheckConstraint("ck_special_hour_intervals_duration", "opens_at <> closes_at");

                            t.HasCheckConstraint("ck_special_hour_intervals_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OmniRest.Api.Data.OwnerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OmniRest.Api.Data.OwnerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniRest.Api.Data.OwnerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OmniRest.Api.Data.OwnerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniRest.Api.Data.BadgeEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishBadgeEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.DishEntity", "Dish")
                        .WithMany("Badges")
                        .HasForeignKey("DishId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniRest.Api.Data.BadgeEntity", "Badge")
                        .WithMany()
                        .HasForeignKey("RestaurantId", "BadgeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MediaAssetEntity", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniRest.Api.Data.MenuCategoryEntity", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId", "MenuId", "RestaurantId")
                        .HasPrincipalKey("Id", "MenuId", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaVariantEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MediaAssetEntity", "MediaAsset")
                        .WithMany("Variants")
                        .HasForeignKey("MediaAssetId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MenuEntity", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Publications")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.PublicationOutboxEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RegularHourIntervalEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("RegularHours")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantAddressEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithOne("Address")
                        .HasForeignKey("OmniRest.Api.Data.RestaurantAddressEntity", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantDomainEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Domains")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.MediaAssetEntity", "MainMediaAsset")
                        .WithMany()
                        .HasForeignKey("MainMediaAssetId", "Id")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainMediaAsset");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantMembershipEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("Memberships")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniRest.Api.Data.OwnerUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantSettingsEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithOne("Settings")
                        .HasForeignKey("OmniRest.Api.Data.RestaurantSettingsEntity", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.SocialLinkEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("SocialLinks")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.SpecialHourEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.RestaurantEntity", "Restaurant")
                        .WithMany("SpecialHours")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("OmniRest.Api.Data.SpecialHourIntervalEntity", b =>
                {
                    b.HasOne("OmniRest.Api.Data.SpecialHourEntity", "SpecialHour")
                        .WithMany("Intervals")
                        .HasForeignKey("SpecialHourId", "RestaurantId")
                        .HasPrincipalKey("Id", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialHour");
                });

            modelBuilder.Entity("OmniRest.Api.Data.DishEntity", b =>
                {
                    b.Navigation("Badges");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MediaAssetEntity", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuCategoryEntity", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("OmniRest.Api.Data.MenuEntity", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("OmniRest.Api.Data.OwnerUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("OmniRest.Api.Data.RestaurantEntity", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Domains");

                    b.Navigation("Memberships");

                    b.Navigation("Menus");

                    b.Navigation("Publications");

                    b.Navigation("RegularHours");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("SocialLinks");

                    b.Navigation("SpecialHours");
                });

            modelBuilder.Entity("OmniRest.Api.Data.SpecialHourEntity", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
