<#
.SYNOPSIS
    One-command launcher for the Omni REST local stack (Windows -> WSL2).

.DESCRIPTION
    Starts PostgreSQL, the .NET API and the Next.js server, waits until both
    answer HTTP, then prints the URLs and the local owner credentials.

    This is a standalone launcher: it deliberately does NOT use
    scripts/local-dev.sh, whose process-ownership check compares
    `ps -o lstart=` strings and therefore breaks under WSL2 -- the reported
    process start time drifts by a second when WSL re-syncs its clock, so the
    supervisor declares a healthy backend dead and tears the stack down.

    Like the supervisor, it never deletes data: no `docker compose down`,
    no `down -v`, no volume removal, no database reset. Stopping only ever
    stops containers and processes.

    Keep this window open. Ctrl-C stops the app and PostgreSQL, preserving data.
    Background processes cannot outlive this window anyway: WSL2 shuts the
    distro down once the last session detaches.

    ON A NEW MACHINE
    Because Windows blocks .ps1 files by default, run start-app.cmd rather than
    this file directly. Prerequisites in WSL (see RUN_LOCALLY_WINDOWS.md):
    Docker Desktop with WSL integration, nvm + the Node version pinned in
    .node-version, the .NET SDK pinned in global.json under ~/.dotnet, plus
    `sudo apt install -y rsync iproute2 lsof curl libatomic1`. The script
    creates the Linux-side copy itself and tells you what is missing.

    The app is built and run from a copy on the Linux filesystem
    ($HOME/projects/omni-rest-infrastructure by default, override with
    OMNIREST_WSL_REPO), because building off /mnt/c is painfully slow. That copy
    is a build target: it is re-mirrored from this working tree on every run, so
    do not edit it -- your changes there would be deleted.

.PARAMETER Command
    run (default) | status | logs | stop

.PARAMETER Rebuild
    Force a fresh frontend production build.

.EXAMPLE
    .\start-app.ps1
    .\start-app.ps1 -Rebuild
    .\start-app.ps1 status
    .\start-app.ps1 stop
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('run', 'status', 'logs', 'stop')]
    [string]$Command = 'run',

    [switch]$Rebuild
)

$ErrorActionPreference = 'Stop'

$Distro   = if ($env:OMNIREST_WSL_DISTRO) { $env:OMNIREST_WSL_DISTRO } else { 'Ubuntu' }
$RepoPath = if ($env:OMNIREST_WSL_REPO)   { $env:OMNIREST_WSL_REPO }   else { '$HOME/projects/omni-rest-infrastructure' }

if (-not (Get-Command wsl.exe -ErrorAction SilentlyContinue)) {
    Write-Error "wsl.exe not found. Install WSL2:  wsl --install -d Ubuntu"
}

$distroList = (wsl.exe --list --quiet) -replace "`0", '' |
    ForEach-Object { $_.Trim() } | Where-Object { $_ }

if ($distroList -notcontains $Distro) {
    Write-Error "WSL distro '$Distro' not found. Available: $($distroList -join ', ')"
}

# The runner is regenerated on every invocation, with LF endings, at a path
# without spaces. Keeping it out of the repo leaves the git tree clean;
# rewriting it every time means it can never drift from this file.
$runner = Join-Path $env:TEMP 'omni-rest-dev-run.sh'

$bash = @'
#!/usr/bin/env bash
# Generated by start-app.ps1 -- edit start-app.ps1, not this file.
# No `set -u`: nvm.sh reads unset variables and would abort the script.
set -o pipefail

ACTION="${1:-run}"
REBUILD="${2:-0}"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$DOTNET_ROOT:$DOTNET_ROOT/tools:$PATH"

REPO="__REPO__"
SRC="__SRC__"

# First run on a new machine: the Linux-side copy does not exist yet. Create it
# empty; the sync step below fills it from the Windows working tree.
if [ ! -d "$REPO" ]; then
  if [ -n "$SRC" ] && [ -d "$SRC" ]; then
    echo "Creating the Linux-side copy at $REPO"
    mkdir -p "$REPO" || { echo "Could not create $REPO"; exit 1; }
  else
    echo "Neither the Linux copy ($REPO) nor the Windows source ($SRC) exists."
    exit 1
  fi
fi
cd "$REPO" || { echo "Cannot enter $REPO"; exit 1; }
nvm use --silent >/dev/null 2>&1 || true

STATE="$REPO/.local-run"
MEDIA="$STATE/media"
BACKEND_DIR="$REPO/src/backend/OmniRest.Api"
BACKEND_DLL="$BACKEND_DIR/bin/Debug/net10.0/OmniRest.Api.dll"
BACKEND_PROJECT="$BACKEND_DIR/OmniRest.Api.csproj"
BACKEND_SOLUTION="$REPO/src/backend/OmniRest.sln"
FRONTEND_DIR="$REPO/src/frontend"
NEXT_BIN="$FRONTEND_DIR/node_modules/next/dist/bin/next"
BACKEND_LOG="$STATE/app-backend.log"
FRONTEND_LOG="$STATE/app-frontend.log"
LOCK_HASH="$STATE/app-npm-lock.sha256"

OWNER_EMAIL="owner@menu.localhost"
OWNER_PASSWORD='OmniRest-Local-2026!'

mkdir -p "$STATE" "$MEDIA"

compose() { docker compose -f "$REPO/compose.yaml" "$@"; }

# curl prints 000 *and* exits non-zero when it cannot connect, so the fallback
# must replace its output, not be appended to it.
http_code() {
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 5 "$@" 2>/dev/null)
  case "$code" in
    ''|*[!0-9]*) printf '000' ;;
    *)           printf '%s' "$code" ;;
  esac
}
backend_code()  { http_code "http://127.0.0.1:5279/"; }
frontend_code() { http_code -H 'Host: menu.localhost' "http://127.0.0.1:3000/"; }

port_busy() { ss -lnt 2>/dev/null | grep -q ":$1 "; }

# ---------- stop / status / logs ---------------------------------------------

stop_stack() {
  # Only ever stops. Never `down`, never `-v`, never touches the volume.
  for f in "$STATE/app-backend.pid" "$STATE/app-frontend.pid"; do
    [ -f "$f" ] || continue
    pid=$(cat "$f" 2>/dev/null)
    case "$pid" in ''|*[!0-9]*) rm -f "$f"; continue ;; esac
    kill "$pid" 2>/dev/null
    for _ in $(seq 1 20); do kill -0 "$pid" 2>/dev/null || break; sleep 0.5; done
    kill -0 "$pid" 2>/dev/null && kill -9 "$pid" 2>/dev/null
    rm -f "$f"
  done
  compose stop postgres >/dev/null 2>&1
}

if [ "$ACTION" = stop ]; then
  echo "Stopping the Omni REST stack (data is preserved)."
  stop_stack
  echo "Stopped."
  exit 0
fi

if [ "$ACTION" = status ]; then
  pg=stopped
  # Match on the compose service name: the container is named
  # "<project>-postgres-1", so a plain 'postgres running' grep never matches.
  compose ps --format '{{.Service}} {{.State}}' 2>/dev/null | grep -q '^postgres running' && pg=running
  echo "Omni REST status"
  printf '  postgres  %s\n' "$pg"
  printf '  backend   HTTP %s  (port 5279)\n' "$(backend_code)"
  printf '  frontend  HTTP %s  (port 3000)\n' "$(frontend_code)"
  exit 0
fi

if [ "$ACTION" = logs ]; then
  tail -n 120 "$BACKEND_LOG" "$FRONTEND_LOG" 2>/dev/null || echo "No logs yet."
  exit 0
fi

# ---------- run ---------------------------------------------------------------

for p in 3000 5279; do
  if port_busy "$p"; then
    echo "Port $p is already in use -- another instance is probably running."
    echo "Stop it first:  .\\start-app.cmd stop"
    exit 1
  fi
done

for c in docker rsync ss node npm dotnet curl; do
  command -v "$c" >/dev/null 2>&1 || {
    echo "Missing required command in WSL: $c"
    echo ""
    echo "This machine is not set up yet. See RUN_LOCALLY_WINDOWS.md in the repo:"
    echo "  node/npm  -> nvm (the repo pins the version in .node-version)"
    echo "  dotnet    -> ~/.dotnet (the repo pins the SDK in global.json)"
    echo "  docker    -> Docker Desktop with WSL integration enabled"
    echo "  rsync/ss  -> sudo apt install -y rsync iproute2"
    echo ""
    echo "Node also needs libatomic1:  sudo apt install -y libatomic1"
    exit 1
  }
done

cleanup() {
  trap - INT TERM EXIT
  echo ""
  echo "Shutting down (data is preserved)..."
  stop_stack
  exit 0
}
trap cleanup INT TERM EXIT

# The app runs from a copy on the Linux filesystem (the repo's own setup guide
# forbids running off /mnt/c). Without this step that copy silently goes stale
# and you run yesterday's code -- e.g. a new admin page missing entirely.
# Build outputs are excluded so builds stay incremental.
echo "==> Syncing source from Windows"
if [ -d "$SRC" ]; then
  # .git is excluded on purpose: the copy is a build target, not a place to run
  # git from, and mirroring it drags along index.lock/HEAD.lock junk.
  changes=$(rsync -rlti --delete \
    --exclude '.git/' --exclude '.local-run/' --exclude 'node_modules/' \
    --exclude '.next/' --exclude 'bin/' --exclude 'obj/' \
    "$SRC/" "$REPO/" | grep -v '^\.')
  if [ -n "$changes" ]; then
    printf '%s\n' "$changes" | awk '{print "    " $NF}' | head -15
    total=$(printf '%s\n' "$changes" | wc -l)
    [ "$total" -gt 15 ] && echo "    ... and $((total - 15)) more"
    if printf '%s\n' "$changes" | grep -q 'src/frontend/'; then
      REBUILD=1
      echo "    frontend changed -> rebuilding"
    fi
  else
    echo "    already up to date"
  fi
else
  echo "    source not found at $SRC -- skipping sync"
fi

# .node-version only exists after the first sync, so select Node again now.
nvm use --silent >/dev/null 2>&1 || true

echo "==> PostgreSQL"
compose up -d --wait postgres || { echo "Could not start PostgreSQL."; exit 1; }

export ASPNETCORE_ENVIRONMENT=Development
export ReverseProxy__KnownProxies__0=127.0.0.1
export MediaStorage__LocalRoot="$MEDIA"

echo "==> Backend build"
dotnet build "$BACKEND_SOLUTION" >>"$BACKEND_LOG" 2>&1 \
  || { echo "Backend build failed. See: $BACKEND_LOG"; tail -n 25 "$BACKEND_LOG"; exit 1; }

echo "==> Database migrations"
dotnet tool restore >>"$BACKEND_LOG" 2>&1
dotnet ef database update --no-build \
  --project "$BACKEND_PROJECT" --startup-project "$BACKEND_PROJECT" \
  >>"$BACKEND_LOG" 2>&1 \
  || { echo "Migrations failed. See: $BACKEND_LOG"; tail -n 25 "$BACKEND_LOG"; exit 1; }

echo "==> Frontend dependencies"
current_hash=$(sha256sum "$FRONTEND_DIR/package-lock.json" | awk '{print $1}')
if [ ! -d "$FRONTEND_DIR/node_modules" ] || [ "$(cat "$LOCK_HASH" 2>/dev/null)" != "$current_hash" ]; then
  ( cd "$FRONTEND_DIR" && npm ci ) >>"$FRONTEND_LOG" 2>&1 \
    || { echo "npm ci failed. See: $FRONTEND_LOG"; tail -n 25 "$FRONTEND_LOG"; exit 1; }
  printf '%s\n' "$current_hash" > "$LOCK_HASH"
else
  echo "    up to date"
fi

echo "==> Frontend build"
if [ "$REBUILD" = 1 ] || [ ! -f "$FRONTEND_DIR/.next/BUILD_ID" ]; then
  ( cd "$FRONTEND_DIR" && npm run build ) >>"$FRONTEND_LOG" 2>&1 \
    || { echo "Frontend build failed. See: $FRONTEND_LOG"; tail -n 25 "$FRONTEND_LOG"; exit 1; }
else
  echo "    reusing existing build (pass -Rebuild to force)"
fi

echo "==> Starting API on 5279"
(
  cd "$BACKEND_DIR"
  exec dotnet "$BACKEND_DLL" --urls http://127.0.0.1:5279
) >>"$BACKEND_LOG" 2>&1 &
BACKEND_PID=$!
echo "$BACKEND_PID" > "$STATE/app-backend.pid"

ready=0
for _ in $(seq 1 90); do
  kill -0 "$BACKEND_PID" 2>/dev/null \
    || { echo "Backend exited during startup. See: $BACKEND_LOG"; tail -n 25 "$BACKEND_LOG"; exit 1; }
  [ "$(backend_code)" != 000 ] && { ready=1; break; }
  sleep 1
done
[ "$ready" = 1 ] || { echo "Backend did not answer on 5279. See: $BACKEND_LOG"; exit 1; }

echo "==> Starting web on 3000"
(
  cd "$FRONTEND_DIR"
  export OMNI_REST_API_BASE_URL=http://127.0.0.1:5279
  export OMNI_REST_FORWARDED_PROTO=https
  exec node "$NEXT_BIN" start --hostname 127.0.0.1 --port 3000
) >>"$FRONTEND_LOG" 2>&1 &
FRONTEND_PID=$!
echo "$FRONTEND_PID" > "$STATE/app-frontend.pid"

ready=0
for _ in $(seq 1 90); do
  kill -0 "$FRONTEND_PID" 2>/dev/null \
    || { echo "Frontend exited during startup. See: $FRONTEND_LOG"; tail -n 25 "$FRONTEND_LOG"; exit 1; }
  [ "$(frontend_code)" = 200 ] && { ready=1; break; }
  sleep 1
done
[ "$ready" = 1 ] || { echo "Frontend did not answer on 3000. See: $FRONTEND_LOG"; exit 1; }

cat <<BANNER

  Omni REST is ready.

  Public:   http://menu.localhost:3000
  Admin:    http://menu.localhost:3000/admin/login
  Email:    $OWNER_EMAIL
  Password: $OWNER_PASSWORD

  Logs:     $BACKEND_LOG
            $FRONTEND_LOG

  Open the URLs in Chrome or Edge -- they resolve *.localhost themselves.
  Keep this window open. Ctrl-C stops the app and PostgreSQL; data is preserved.

BANNER

# Liveness watch. Uses kill -0 on our own children rather than comparing
# `ps -o lstart=` strings, which drift under WSL2 and produce false deaths.
while :; do
  kill -0 "$BACKEND_PID"  2>/dev/null || { echo "Backend stopped. See: $BACKEND_LOG";   tail -n 25 "$BACKEND_LOG";  exit 1; }
  kill -0 "$FRONTEND_PID" 2>/dev/null || { echo "Frontend stopped. See: $FRONTEND_LOG"; tail -n 25 "$FRONTEND_LOG"; exit 1; }
  sleep 2
done
'@

# This script lives in the repo root, so the Windows working tree to mirror is
# simply its own directory. Override with OMNIREST_WIN_REPO if you keep the
# script somewhere else.
$WinRepo = if ($env:OMNIREST_WIN_REPO) { $env:OMNIREST_WIN_REPO } else { $PSScriptRoot }

if (Test-Path $WinRepo) {
    $full = (Resolve-Path $WinRepo).Path
    $linuxSrc = '/mnt/' + $full.Substring(0,1).ToLower() + $full.Substring(2).Replace('\','/')
} else {
    Write-Warning "Windows repo not found at $WinRepo -- the WSL copy will not be synced."
    $linuxSrc = ''
}

$bash = $bash.Replace('__REPO__', $RepoPath).Replace('__SRC__', $linuxSrc).Replace("`r`n", "`n")
[IO.File]::WriteAllText($runner, $bash, (New-Object Text.UTF8Encoding $false))

$linuxRunner = '/mnt/' + $runner.Substring(0,1).ToLower() + $runner.Substring(2).Replace('\','/')
$rebuildFlag = if ($Rebuild) { '1' } else { '0' }

if ($Command -eq 'run') {
    Write-Host ''
    Write-Host '  Starting Omni REST in WSL. Keep this window open.' -ForegroundColor Cyan
    Write-Host '  Ctrl-C stops everything without deleting data.' -ForegroundColor Cyan
    Write-Host ''
}

& wsl.exe -d $Distro -- bash $linuxRunner $Command $rebuildFlag
exit $LASTEXITCODE
